development:
  adapter: postgresql
  encoding: utf8
  database: query_development
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: utf8
  database: query_test
  host: localhost
  min_messages: WARNING
